In [29]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Barbara Youngkeit\Desktop\SQL\CSV\invoices.csv")

C:\Users\Barbara Youngkeit\AppData\Local\Temp\ipykernel_16724\2785870142.py:2: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\Barbara Youngkeit\Desktop\SQL\CSV\invoices.csv")

In [30]:
df.shape

(230548, 14)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230548 entries, 0 to 230547
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   InvoiceLineID   230548 non-null  int64
 1   InvoiceID       230548 non-null  int64
 2   StockItemID     230087 non-null  float64
 3   Description     229876 non-null  object
 4   PackageTypeID   230548 non-null  int64
 5   Quantity        230548 non-null  int64
 6   UnitPrice       230548 non-null  float64
 7   TaxRate         230548 non-null  int64
 8   TaxAmount       109623 non-null  float64
 9   LineProfit      230548 non-null  float64
 10  ExtendedPrice   113081 non-null  float64
 11  LastEditedBy    230548 non-null  int64
 12  LastEditedWhen  6 non-null       object
 13  Customer        230548 non-null  object
dtypes: float64(5), int64(6), object(3)
memory usage: 24.6+ MB

In [10]:
df.describe()

,InvoiceLineID,InvoiceID,StockItemID,PackageTypeID,Quantity,UnitPrice,TaxRate,TaxAmount,LineProfit,ExtendedPrice,LastEditedBy
count,230548.000000,230548.000000,230087.000000,230548.000000,230548.000000,230548.000000,230548.000000,109623.000000,230548.00000,113081.000000,230548.000000
mean,114127.066880,35177.386891,110.181827,7.073638,39.252524,45.539361,14.463409,113.328006,375.38894,740.092626,10.800480
std,65900.142929,20338.920057,63.722514,0.644528,55.193934,139.510031,3.904056,221.866696,753.17041,1705.229089,5.509623
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.660000,-15.000000,0.380000,-645.00000,-999.000000,2.000000
25%,57062.750000,17570.000000,54.000000,7.000000,5.000000,13.000000,15.000000,14.400000,51.00000,89.700000,6.000000
50%,114130.500000,35151.000000,111.000000,7.000000,10.000000,18.000000,15.000000,34.500000,120.00000,248.400000,11.000000
75%,171203.250000,52766.000000,165.000000,7.000000,60.000000,32.000000,15.000000,129.600000,390.00000,919.080000,16.000000
max,228265.000000,70510.000000,227.000000,10.000000,3150.000000,1899.000000,15.000000,14994.000000,9200.00000,114954.000000,20.000000

In [31]:
df.loc[df['TaxRate'] < 0, 'TaxRate'] *= -1
df.loc[df['ExtendedPrice'] < 0, 'ExtendedPrice'] *= -1

In [32]:
df['Customer'].value_counts()

Customer
Terry's Trinkets       85593
Stuff by Stew          62752
Stuf by Stew           31984
Wholesaler Plus        15735
Big Buys Retail        13461
Terry's Trinket         9483
stuff by stew           7068
Dennis Distribution     4472
Name: count, dtype: int64

In [33]:
df.drop(columns=['LastEditedWhen'],inplace = True)

In [35]:
df.shape

(230548, 13)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 230548 entries, 0 to 230547
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   InvoiceLineID  230548 non-null  int64
 1   InvoiceID      230548 non-null  int64
 2   StockItemID    230087 non-null  float64
 3   Description    229876 non-null  object
 4   PackageTypeID  230548 non-null  int64
 5   Quantity       230548 non-null  int64
 6   UnitPrice      230548 non-null  float64
 7   TaxRate        230548 non-null  int64
 8   TaxAmount      109623 non-null  float64
 9   LineProfit     230548 non-null  float64
 10  ExtendedPrice  113081 non-null  float64
 11  LastEditedBy   230548 non-null  int64
 12  Customer       230548 non-null  object
dtypes: float64(5), int64(6), object(2)
memory usage: 22.9+ MB

In [41]:
df[df['StockItemID'].isnull() & df['Description'].isnull()]

Empty DataFrame
Columns: [InvoiceLineID, InvoiceID, StockItemID, Description, PackageTypeID, Quantity, UnitPrice, TaxRate, TaxAmount, LineProfit, ExtendedPrice, LastEditedBy, Customer]
Index: []

In [42]:
df.dropna(subset=['StockItemID', 'Description'], how='all', inplace=True)

In [43]:
df.shape

(230087, 13)

In [44]:
df.describe()

,InvoiceLineID,InvoiceID,StockItemID,PackageTypeID,Quantity,UnitPrice,TaxRate,TaxAmount,LineProfit,ExtendedPrice,LastEditedBy
count,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,109408.000000,230087.000000,112858.000000,230087.000000
mean,114131.169266,35178.644621,110.181827,7.073468,39.247267,45.532654,14.977248,113.294589,375.314843,877.757713,10.799919
std,65894.369187,20337.134754,63.722514,0.644395,55.193231,139.461436,0.336518,221.796355,753.072527,1637.875187,5.509919
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.660000,10.000000,0.380000,-645.000000,2.880000,2.000000
25%,57077.500000,17574.000000,54.000000,7.000000,5.000000,13.000000,15.000000,14.400000,51.000000,119.600000,6.000000
50%,114131.000000,35151.000000,111.000000,7.000000,10.000000,18.000000,15.000000,34.500000,120.000000,294.980000,11.000000
75%,171196.500000,52764.000000,165.000000,7.000000,60.000000,32.000000,15.000000,129.600000,390.000000,999.000000,16.000000
max,228265.000000,70510.000000,227.000000,10.000000,3150.000000,1899.000000,15.000000,14994.000000,9200.000000,114954.000000,20.000000

In [45]:
df['TaxAmount'] = df['UnitPrice'] * df['Quantity'] * df['TaxRate'] / 100

In [49]:
df.describe()

,InvoiceLineID,InvoiceID,StockItemID,PackageTypeID,Quantity,UnitPrice,TaxRate,TaxAmount,LineProfit,ExtendedPrice,LastEditedBy
count,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,230087.000000,112858.000000,230087.000000
mean,114131.169266,35178.644621,110.181827,7.073468,39.247267,45.532654,14.977248,112.952119,375.314843,877.757713,10.799919
std,65894.369187,20337.134754,63.722514,0.644395,55.193231,139.461436,0.336518,219.486822,753.072527,1637.875187,5.509919
min,1.000000,1.000000,1.000000,1.000000,1.000000,0.660000,10.000000,0.375000,-645.000000,2.880000,2.000000
25%,57077.500000,17574.000000,54.000000,7.000000,5.000000,13.000000,15.000000,14.400000,51.000000,119.600000,6.000000
50%,114131.000000,35151.000000,111.000000,7.000000,10.000000,18.000000,15.000000,34.500000,120.000000,294.980000,11.000000
75%,171196.500000,52764.000000,165.000000,7.000000,60.000000,32.000000,15.000000,129.600000,390.000000,999.000000,16.000000
max,228265.000000,70510.000000,227.000000,10.000000,3150.000000,1899.000000,15.000000,14994.000000,9200.000000,114954.000000,20.000000

In [50]:
df['ExtendedPrice'] = df['UnitPrice'] * df['Quantity'] + df['TaxAmount']

In [58]:
average_ep = df['ExtendedPrice'].mean()
std_dev_ep = df['ExtendedPrice'].std()
average_qty = df['Quantity'].mean()
std_dev_qty = df['Quantity'].std()

In [60]:
df['Z-Score'] = (df['ExtendedPrice'] - average_ep) / std_dev_ep
df['Z-Scoreq'] = (df['Quantity'] - average_qty) / std_dev_qty
df.head(1)

,InvoiceLineID,InvoiceID,StockItemID,Description,PackageTypeID,Quantity,UnitPrice,TaxRate,TaxAmount,LineProfit,ExtendedPrice,LastEditedBy,Customer,Z-Score,Z-Scoreq
0,1,1,67.0,Ride on toy sedan car (Black) 1/12 scale,7,10,230.0,15,345.0,850.0,2645.0,7,Stuff by Stew,1.055963,-0.529907

In [61]:
df.loc[df['Z-Scoreq'] > 3]

,InvoiceLineID,InvoiceID,StockItemID,Description,PackageTypeID,Quantity,UnitPrice,TaxRate,TaxAmount,LineProfit,ExtendedPrice,LastEditedBy,Customer,Z-Score,Z-Scoreq
122,123,59,191.0,Black and orange fragile despatch tape 48mmx75m,7,288,3.70,15,159.84,547.2,1225.44,9,Terry's Trinkets,0.212577,4.506943
197,198,95,191.0,Black and orange fragile despatch tape 48mmx75m,7,252,3.70,15,139.86,478.8,1072.26,9,stuff by stew,0.121570,3.854689
298,299,129,196.0,Black and orange handle with care despatch tap...,7,216,4.10,15,132.84,453.6,1018.44,2,Stuf by Stew,0.089595,3.202435
305,306,132,186.0,Shipping carton (Brown) 457x457x457mm,7,250,2.10,15,78.75,250.0,603.75,2,Big Buys Retail,-0.156780,3.818453
307,308,134,189.0,Clear packaging tape 48mmx75m,7,234,2.90,15,101.79,280.8,780.39,2,Terry's Trinkets,-0.051835,3.528562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230285,171205,52767,183.0,Shipping carton (Brown) 480x270x320mm,7,250,2.74,15,102.75,385.0,787.75,17,Terry's Trinkets,-0.047462,3.818453
230377,74832,23009,182.0,Shipping carton (Brown) 457x279x279mm,7,250,1.28,15,48.00,170.0,368.00,10,Stuf by Stew,-0.296843,3.818453
230458,151681,46729,195.0,Black and orange handle with care despatch tap...,7,216,3.70,15,119.88,518.4,919.08,5,Terry's Trinkets,0.030563,3.202435
230475,217008,67029,201.0,Red and white urgent despatch tape 48mmx75m,7,240,3.70,15,133.20,504.0,1021.20,18,Stuff by Stew,0.091234,3.637271
230510,154951,47750,201.0,Red and white urgent despatch tape 48mmx75m,7,240,3.70,15,133.20,504.0,1021.20,17,Big Buys Retail,0.091234,3.637271

In [62]:
df.loc[df['Z-Score'] > 3]

,InvoiceLineID,InvoiceID,StockItemID,Description,PackageTypeID,Quantity,UnitPrice,TaxRate,TaxAmount,LineProfit,ExtendedPrice,LastEditedBy,Customer,Z-Score,Z-Scoreq
96,97,45,164.0,32 mm Double sided bubble wrap 50m,7,50,112.0,15,840.00,2650.0,6440.00,9,Stuf by Stew,3.310639,0.194820
111,112,53,170.0,20 mm Anti static bubble wrap (Blue) 50m,7,90,102.0,15,1377.00,4230.0,10557.00,9,Stuf by Stew,5.756622,0.919546
124,125,59,167.0,10 mm Anti static bubble wrap (Blue) 50m,7,60,99.0,15,891.00,3240.0,6831.00,9,Terry's Trinkets,3.542939,0.376001
256,257,116,167.0,10 mm Anti static bubble wrap (Blue) 50m,7,70,99.0,15,1039.50,3780.0,7969.50,9,Stuf by Stew,4.219342,0.557183
289,290,126,158.0,10 mm Double sided bubble wrap 50m,7,90,105.0,15,1417.50,4410.0,10867.50,9,Terry's Trinkets,5.941096,0.919546
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230065,151133,46554,158.0,10 mm Double sided bubble wrap 50m,7,90,105.0,15,1417.50,4410.0,10867.50,13,Dennis Distribution,5.941096,0.919546
230079,219963,67961,167.0,10 mm Anti static bubble wrap (Blue) 50m,7,80,99.0,15,1188.00,4320.0,9108.00,19,Terry's Trinkets,4.895746,0.738365
230298,217447,67164,158.0,10 mm Double sided bubble wrap 50m,7,60,105.0,15,945.00,2940.0,7245.00,8,Terry's Trinkets,3.788904,0.376001
230407,209037,64540,158.0,10 mm Double sided bubble wrap 50m,7,100,105.0,15,1575.00,4900.0,12075.00,17,Dennis Distribution,6.658493,1.100728
230483,1708,598,215.0,Air cushion machine (Blue),7,5,1899.0,15,1424.25,3795.0,10919.25,15,Terry's Trinkets,5.971841,-0.620498

In [63]:
df[df.duplicated(subset=['InvoiceID', 'InvoiceLineID'])]

,InvoiceLineID,InvoiceID,StockItemID,Description,PackageTypeID,Quantity,UnitPrice,TaxRate,TaxAmount,LineProfit,ExtendedPrice,LastEditedBy,Customer,Z-Score,Z-Scoreq
228265,199860,61652,222.0,Chocolate beetles 250g,1,216,8.55,10,184.6800,820.8,2031.4800,5,Stuff by Stew,0.691460,3.202435
228266,197512,60915,161.0,20 mm Double sided bubble wrap 50m,7,50,108.00,15,810.0000,4600.0,6210.0000,12,Stuf by Stew,3.173992,0.194820
228267,113602,34985,167.0,10 mm Anti static bubble wrap (Blue) 50m,7,40,99.00,15,594.0000,2160.0,4554.0000,4,Stuf by Stew,2.190133,0.013638
228268,6306,1950,184.0,Shipping carton (Brown) 305x305x305mm,7,100,3.50,15,52.5000,160.0,402.5000,16,stuff by stew,-0.276346,1.100728
228269,134380,41395,155.0,Large sized bubblewrap roll 50m,7,50,24.00,15,180.0000,550.0,1380.0000,20,Stuff by Stew,0.304404,0.194820
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230543,36558,11285,139.0,Furry animal socks (Pink) M,10,36,5.00,15,27.0000,126.0,207.0000,20,Wholesaler Plus,-0.392496,-0.058835
230544,21110,6502,9.0,USB food flash drive - banana,7,2,32.00,15,9.6000,40.0,73.6000,10,stuff by stew,-0.471752,-0.674852
230545,34087,10504,179.0,Shipping carton (Brown) 229x229x229mm,7,125,1.05,15,19.6875,62.5,150.9375,16,Terry's Trinket,-0.425804,1.553682
230546,103435,31836,20.0,DBA joke mug - you might be a DBA if (White),7,1,13.00,15,1.9500,8.5,14.9500,20,Big Buys Retail,-0.506597,-0.692970
230547,192963,59503,70.0,Ride on toy sedan car (Green) 1/12 scale,7,5,230.00,15,172.5000,425.0,1322.5000,4,Stuff by Stew,0.270242,-0.620498

In [64]:
df.drop_duplicates(subset=['InvoiceID', 'InvoiceLineID'], keep='first', inplace=True)

In [65]:
df.shape

(227811, 15)

In [90]:
values = df.groupby('Description')['Quantity'].sum()
values.sort_values(ascending=False).head(1)

Description
Black and orange fragile despatch tape 48mmx75m    207108
Name: Quantity, dtype: int64

In [91]:
profit = df.groupby('Description')['LineProfit'].sum()
profit.sort_values(ascending=False).head(1)

Description
20 mm Double sided bubble wrap 50m    5283560.0
Name: LineProfit, dtype: float64

In [93]:
order = df.groupby('Description')['Quantity'].mean()
order.sort_values(ascending=False).head(1)

Description
Black and orange fragile despatch tape 48mmx75m    199.526012
Name: Quantity, dtype: float64